const fs = require('fs');
let content = fs.readFileSync('src/pages/ProductDetails.tsx', 'utf8');

const oldLogic = `        // Use the proper thumbnail generated by the server
        const updated = { 
             ...product, 
             images: [primary, ...product.images],
            thumbnails: [thumbnail, ...product.thumbnails]
        };`;

const newLogic = `        // Use the proper thumbnail generated by the server
        const updatedImages = [...product.images];
        updatedImages[activeImageIndex] = primary;
        
        const updatedThumbnails = [...(product.thumbnails || [])];
        updatedThumbnails[activeImageIndex] = thumbnail;

        const updated = { 
             ...product, 
             images: updatedImages,
            thumbnails: updatedThumbnails
        };`;

if (content.includes(oldLogic)) {
    content = content.replace(oldLogic, newLogic);
    fs.writeFileSync('src/pages/ProductDetails.tsx', content);
    console.log("Replaced handleApplyAI array logic successfully!");
} else {
    console.log("Could not find TargetContent in handleApplyAI");
}
